parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    REPO_DIR: 'scikit-learn'
    BUILD_COMMIT: '0.20.3'
    PLAT: 'x86_64'
    UNICODE_WIDTH: '32'
    NP_BUILD_DEP: 'numpy==1.8.2'
    NP_TEST_DEP: 'numpy==1.13.1'
    CYTHON_BUILD_DEP: 'cython==0.28.5'
    CYTHON_TEST_DEP: 'cython'
    SCIPY_BUILD_DEP: 'scipy'
    SCIPY_TEST_DEP: 'scipy'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - checkout: self
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(MB_PYTHON_VERSION)
      displayName: Set python version
    - script: |
        pip install virtualenv
      displayName: Install virtualenv
    - script: |
        echo "Building scikit-learn-$BUILD_COMMIT"
        BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP $SCIPY_BUILD_DEP"
        TEST_DEPENDS="$NP_TEST_DEP pytest $CYTHON_TEST_DEP $SCIPY_TEST_DEP"
        source multibuild/common_utils.sh
        source multibuild/travis_steps.sh
        before_install
        if [[ $TRAVIS_OS_NAME = "osx" ]]; then enable_openmp; fi
        clean_code $REPO_DIR $BUILD_COMMIT
        build_wheel $REPO_DIR $PLAT
        if [[ $TRAVIS_OS_NAME = "osx" ]]; then disable_system_openmp; fi
        # install_run $PLAT
      displayName: Build
      env:
        TRAVIS_OS_NAME: ${{ parameters.name }}
    - script: |
        pip install wheelhouse-uploader
        ls "$(AGENT_WORKFOLDER)/wheelhouse"





