env:
  global:
      - REPO_DIR="scikit-learn"
      - BUILD_COMMIT=0.20.1
      - UNICODE_WIDTH=32
      - SCIPY_BUILD_DEP="scipy"
      - SCIPY_TEST_DEP="scipy"
      - TEST_BUILDS=1
      - PLAT=aarch64
      - MB_ML_VER=2014
      - DOCKER_TEST_IMAGE=multibuild/xenial_aarch64

language: python
python: 3.6
sudo: required
services: docker

matrix:
  include:
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_TEST_DEP=numpy==1.13.1
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.14.5
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.3

before_install:
    - BUILD_DEPENDS="$NP_BUILD_DEP cython $SCIPY_BUILD_DEP"
    - TEST_DEPENDS="$NP_TEST_DEP pytest $SCIPY_TEST_DEP"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # - pip install wheelhouse-uploader
    # - python -m wheelhouse_uploader upload --local-folder
    #       ${TRAVIS_BUILD_DIR}/wheelhouse/
    #       --no-update-index
    #       wheels
