language: python

jobs:
  include:
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64

install:
  - python3 -m pip install cibuildwheel==1.6.4

script:
  # build the wheels, put them into './wheelhouse'
  - cd scikit-learn
  - git checkout 0.23.2
  - python3 -m cibuildwheel --output-dir wheelhouse
