jobs:
- template: azure/posix.yml
  parameters:
    name: linux
    vmImage: ubuntu-16.04
    matrix:
      py3.7:
        NP_BUILD_DEP: 'numpy==1.14.5'
        NP_TEST_DEP: 'numpy==1.14.5'
        MB_PYTHON_VERSION: '3.7'


- job: Upload-pypi
  dependsOn: linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'linux-py3.7'
      targetPath: $(System.DefaultWorkingDirectory)
  - script: |
      ls

