on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version upload to pypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Publishing: ${{ github.event.inputs.version }}"
